- name: installing unzip
  package:
     name: unzip

- name: installing teraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.1.2/terraform_1.1.2_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    owner: root
    group: root
    mode: 0755
